'use strict'

var casual = require('casual')
var totalUsersToFake = 200
const servicesWithCategory = {
  'HTML Tutor': 1,
  'CSS Tutor': 1,
  'SQL Tutoring': 1,
  'Python 3 Tutoring': 1,
  'Java Tutoring': 1,
  'Japanese Tutor': 1,
  'Javascript Tutoring': 1,
  'Algebra Tutoring': 1,
  'SAT Tutoring': 1,
  'ACT Tutoring': 1,
  'Express.js Tutoring': 1,
  'React.js Tutoring': 1,
  'Cantonese Translator': 1,
  'Node Tutoring': 1,
  'Redux.js Tutoring': 1,
  'Vocal Lessons': 2,
  'Piano Lessons': 2,
  'Jazz Lessons': 2,
  'Guitar Lessons': 2,
  'Music Production': 2,
  'Hair-Cutting': 3,
  'Tattoo Design': 3,
  'Nail Technician': 3,
  'Hair Stylist': 3,
  'Make-up': 3,
  'Personal Bartender': 3,
  'Personal Stylist': 3,
  Modeling: 3,
  'Physical Therapy': 4,
  'Psychological Therapy': 4,
  'House Makeover': 5,
  'Lawn Mowing': 5,
  'Taking Out The Trash': 5,
  'Window Cleaning': 5,
  'House Keeping': 5,
  'Doing The Dishes': 5,
  Nanny: 5,
  'Personal Chef': 5,
  'Interior Design': 5,
  'Basketball Lessons': 6,
  'Personal Training': 6,
  'Picture Taking': 7,
  'Caricature Drawing': 7,
  'Financial Analysis': 8,
  'Photoshopping Any Image': 8,
  'Meditation Practice': 9,
  'Help Doing Taxes': 9,
  'Personal Nutritionist': 9,
  'Social Skill Tutor': 9,
  'Personal Hype Man': 9,
  'Life Makeover': 9,
  'Travel Guide': 9
}
const servicesList = Object.keys(servicesWithCategory)

const reviewList = [
  'Trash',
  'Great',
  'Not my style, but might be good for others',
  'Really genuine person. Cannot wait to see them again',
  'Too serious',
  'Needs to wear deodorant',
  'Amazing experience',
  'Had lots of fun',
  'Would definitely recommend!',
  'Wow',
  'Kind of an awkward person',
  'Very skilled and also a great communicator',
  'Overall OK',
  'Great communication skills',
  'Very Polite',
  'Trustworthy',
  'Great Swap',
  'Good person',
  'Bad hygiene',
  'Great enthusiasm',
  'Good insight',
  'Overall satisfied with the swap',
  'Good job!',
  'Thanks!',
  'Hope to see you again soon!',
  'Would highly recommend',
  'Would highly discourage from swapping with this person',
  'Argumentative',
  'Untrustworthy vibes',
  'Bad swap',
  'Overall OK swap',
  'Not my vibe',
  'Was not as good as I expected',
  'Such a genuine person.',
  'Has a positive energy',
  'Has a contagious positive energy',
  'Was very lucky to meet this person',
  'Amazing',
  'Good conversation'
]

const imageUrls = [
  'https://ca.slack-edge.com/T024FPYBQ-UNVS3D1CL-72903580eea7-512',
  'https://ca.slack-edge.com/T024FPYBQ-U4837KX9Q-6cf4b0197f03-512',
  'https://ca.slack-edge.com/T024FPYBQ-U0T06NJ3X-38881f57d249-512',
  'https://ca.slack-edge.com/T024FPYBQ-ULLV05XDF-2fe0cba62c9e-512',
  'https://ca.slack-edge.com/T024FPYBQ-UPQMR7DMZ-658921fc3d6e-512',
  'https://ca.slack-edge.com/T024FPYBQ-UPQMRBT6F-efbb1cb56141-512',
  'https://ca.slack-edge.com/T024FPYBQ-UPU8R9EPK-cd2a22172359-512',
  'https://ca.slack-edge.com/T024FPYBQ-ULT9G51KJ-9663832b4ebe-512',
  'https://ca.slack-edge.com/T024FPYBQ-UMRL9PW56-d9abe093b390-512',
  'https://ca.slack-edge.com/T024FPYBQ-U024FPYBS-gcd5248cc625-512',
  'https://ca.slack-edge.com/T024FPYBQ-ULSR7KVMJ-135ef8ab4809-512',
  'https://ca.slack-edge.com/T024FPYBQ-UQ265EK40-gab148043d14-512',
  'https://ca.slack-edge.com/T024FPYBQ-U6C9ZFFK2-g56bb2d17402-512',
  'https://ca.slack-edge.com/T024FPYBQ-UPU8R414H-113762322dc0-512',
  'https://ca.slack-edge.com/T024FPYBQ-U028RRRRH-ga46faf6969c-512',
  'https://ca.slack-edge.com/T024FPYBQ-UM9DQ1L5A-27124cabfef7-512',
  'https://ca.slack-edge.com/T024FPYBQ-UQ1MX514L-b770aa7afde7-512',
  'https://ca.slack-edge.com/T024FPYBQ-ULVE17K1U-9c9fc00aa4e7-512',
  'https://ca.slack-edge.com/T024FPYBQ-U028EUYFP-34357868f35c-512',
  'https://ca.slack-edge.com/T024FPYBQ-UAV23HH2A-db862acd7a95-512',
  'https://ca.slack-edge.com/T024FPYBQ-UKF6C461L-8e3bd8dd922e-512',
  'https://ca.slack-edge.com/T024FPYBQ-UH3RW9YE9-10586ff2ce97-512',
  'https://ca.slack-edge.com/T024FPYBQ-UQ265BSKS-2cf611e071cc-512',
  'https://ca.slack-edge.com/T024FPYBQ-UJV3UUK32-f8acca72f250-512',
  'https://ca.slack-edge.com/T024FPYBQ-UDPFZ5N5R-88905aa80df5-512',
  'https://ca.slack-edge.com/T024FPYBQ-UQ41YD63Z-f43a7eabb457-512',
  'https://ca.slack-edge.com/T024FPYBQ-UPPCHCB42-3fa355f24901-512',
  'https://ca.slack-edge.com/T024FPYBQ-UBV6KAPMZ-992b2fa4a605-512',
  'https://ca.slack-edge.com/T024FPYBQ-UP6B6RNUS-fa4f60e626b2-512',
  'https://ca.slack-edge.com/T024FPYBQ-UPQMR0MFV-5ad2bc53e607-512',
  'https://ca.slack-edge.com/T024FPYBQ-UQ4CB7UAJ-gb42a8699b6f-512',
  'https://ca.slack-edge.com/T024FPYBQ-UHF7SFX1P-71576b1c3c80-512'
]

const interestsList = [
  'Baseball',
  'Cooking',
  'Pottery',
  'Comedy Clubs',
  'Skiing',
  'Talking',
  'Myspace',
  'TikTok',
  'Owl Watching',
  'Ice Cream',
  'Playing I Spy',
  'Apple Products',
  'Golf',
  'Country Clubbing',
  'Netflix',
  'Mathas Vineyard',
  'Reading',
  'Going to The Zoo',
  'Aquariums',
  'DOTA 2',
  'Bragging',
  'Shoplifting',
  'Meditation',
  'Watches',
  'Laundry',
  '2048',
  'Jewelry',
  'Joker Movie',
  'Elon Musk',
  'Highschool Musical',
  'Dinosaurs',
  'Bird Watching',
  'The Incredibles 1',
  'Nintendo Switch',
  'Super Smash Bros',
  'Flexing',
  'Machine Learning',
  'Apple Maps',
  'Boggle With Friends',
  'Scrabble With Friends',
  'Farmville: Darkness Rising',
  'Sims 3: Unrated',
  'Playing the Piano',
  'Teletubbies',
  'Boo-Bah',
  'Barney and Friends',
  'Rob Fox',
  'Hanging out with Eric Yang',
  'Running Marathons',
  'Avengers On Ice',
  'Traveling',
  'AlgoExpert',
  'LeetCode',
  'Transformers 2: The Musical',
  'Gambling',
  'Winnie The Pooh: Darkness Rising',
  'Squash',
  'Bocceball',
  'Volleyball',
  'Polo',
  "Where's Waldo?",
  'Jim Carrey',
  'Pet Ownership',
  'Sailing',
  'Greek Fodd',
  'Drinking Prosecco',
  'Vineyard Vines',
  'Patagonia',
  'Personal Training',
  'Snowball Fighting',
  'Pescatarianism',
  'Veganism',
  'Fast Food',
  'Bitcoin',
  'Shoe Shopping',
  'Cracking Jokes',
  '5Gum',
  'Germophobia',
  'Razor Scooters',
  'Competitve Tickling',
  'James Bond',
  'Club Getaway',
  'Club Med',
  'Getting Spray Tans',
  'Getting my nails done',
  'Giving Fist Bumps',
  'Cheech and Chong',
  'Cardio',
  'Tarantino',
  'Eternal Sunshine of a Spotless Mind',
  'Pasta with butter',
  'Glassblowing',
  'Being kind',
  'Painting Large Paintings',
  'Drawing',
  'Living In The Darkness(Shadows)',
  'Teleworking',
  'The American Flag',
  'Philanthropy',
  'Acrobatics',
  'Building Furniture',
  'Learning',
  'Shopping',
  'Lock Picking',
  'Eating a lot',
  'Career Development',
  'Cleaning the house',
  'Washing dishes',
  'Video Games',
  'Basketball',
  'Anime',
  'Comics',
  'Film',
  'Painting',
  'Dance',
  'Martial Arts',
  'Computer Programming',
  'Scuba Diving',
  'Biking',
  'Rock Climbing',
  'Hiking',
  'Dodgeball',
  'Kickball',
  'Kickboxing',
  'MMA',
  'Kung Fu-Movies',
  'Psychology',
  'Comedy',
  'History',
  'WW2',
  'The American Civil War',
  'Fashion',
  'Card Tricks',
  'Weightlifting',
  'Board Games',
  'Yu-Gi-Oh',
  'Pokemon',
  'Drowning My Demons',
  'Staring At the Ceiling',
  'Pretending',
  'Projecting',
  'Having friends',
  'Water Polo',
  'Swimming',
  'Watching Movies',
  'Getting tea',
  'Ramen',
  'Enlightenment',
  'Yoga',
  'Alternative Music',
  'Deep Conversations',
  'Doing Nails',
  'Getting my hair done',
  'Gossiping',
  'Vibing',
  'White Noise',
  'Chilling',
  'Hanging out',
  'Listening to music',
  'Trumbone',
  'Violin',
  'Competitive Sky Diving',
  'Listening to Drake',
  'Talking about Money on my bluetooth in financial district',
  'Pasta with sauce',
  'Being deep',
  'Talking about space and aliens and other deep topics',
  'Crying to Drake',
  'Algos',
  'Ping Pong Tournaments',
  'Gaming',
  'Dungeons And Dragons',
  'Crying in The Shower',
  'Magic Tricks',
  'Magic The Gathering',
  'Body Building',
  'Science Experiments',
  'Learning languages',
  'Boxing',
  'Choir',
  'Soccer',
  'Checking stocks and having no insight',
  'Reading about Start-Ups',
  'Debating',
  'Voting',
  'Prank Calling',
  'Making memes',
  'Hanging out with my stuffed animals',
  'The Illuminati',
  'Cults',
  'Secret Societies',
  'Drinking coffee',
  'Making coffee',
  'Selling used goods',
  'Politics',
  'Banking',
  'Doing my taxes',
  'Commuting',
  'Urban exploring',
  'Baking',
  'Fishing',
  'Competitve Fishing',
  'Bowling',
  'Streetwear',
  'Searching for meaning',
  'Meetups',
  'Networking',
  'LinkedIn',
  'Practicing my pitch',
  'Working on my resume',
  'Being productive at work',
  'Non-matching socks'
]

const numberOfServices = 154
function generateReviews() {
  const reviews = []
  for (let i = 0; i < 1000; i++) {
    reviews.push({
      rating: 2 + Math.ceil(Math.random() * 3) * 1.0,
      comment: reviewList[Math.floor(Math.random() * reviewList.length)],
      serviceId: Math.ceil(Math.random() * numberOfServices),
      userId: Math.ceil(Math.random() * (totalUsersToFake + 4))
    })
  }
  return reviews
}

function generateUsers(num) {
  const users = []
  for (let i = 5; i < num + 5; i++) {
    const firstName = casual.first_name
    const lastName = casual.last_name
    users.push({
      firstName,
      lastName,
      email: `${firstName + lastName}@email.com`,
      phoneNumber: casual.phone,
      password: '123',
      bio: casual.sentences(2),
      zipCode: Number(casual.zip(5)),
      photo: imageUrls[Math.floor(Math.random() * imageUrls.length)]
      // overallRating: 1 + 4 * Math.random(),
      // reviewCount: 1
    })
  }
  return users
}

function generateServices(num) {
  const services = []
  const name = servicesList[Math.floor(Math.random() * servicesList.length)]
  for (let i = 5; i < num * 3 + 5; i++) {
    services.push({
      userId: 1 + Math.floor(Math.random() * (num + 4)),
      name: name,
      description: casual.text,
      proficiency: Math.ceil(Math.random() * 3),
      remote: casual.coin_flip,
      serviceCategoryId: servicesWithCategory[name]
      // serviceRating: Math.floor(5 * Math.random()),
      // reviewCount: 1
    })
  }
  return services
}

const fakeUsers = generateUsers(totalUsersToFake)
const fakeServices = generateServices(totalUsersToFake)
const fakeReviews = generateReviews(numberOfServices)

module.exports = {
  fakeUsers,
  fakeServices,
  generateUsers,
  generateServices,
  fakeReviews,
  interestsList
}
